import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useQuery, gql} from '@apollo/client'

const GET_LOCATIONS = gql`
  query GetLocations {
    locations {
      id
      name
      description
      photo
    }
  }
`

export default function Home() {
  const { loading, data, error } = useQuery(GET_LOCATIONS)
  console.log(error)
  console.log(loading)
  console.log(data)
  if (loading) {
    return (
    <p className={styles.description}>
    Loading
    <code className={styles.code}>pages/index.js</code>
  </p>)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          My first Apollo app 🚀
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {
            data.locations.map(({id, name, description, photo}) => (
              <div key={id} className={styles.card}>
                <h2>{name}</h2>
                <img width="100%" height="100%" src={`${photo}`} alt="" /><br />
                <b>About this location:</b>
                <p>{description}</p><br />
              </div>
            ))
          }
          
           
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
